<?php

declare(strict_types=1);

/** @var Escaper $escaper */
/** @var Template $block */
/** @var PayPo $magewire */

/** @var Php $this */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\TemplateEngine\Php;
use Snowdog\Hyva\Checkout\PayNow\Payment\Method\PayPo;
?>
<div class="payment-method">

    <div class="paynow-data-processing-info">
        <?php foreach ($magewire->getGdprNotices() as $notice): ?>
            <div
                class="paynow-data-processing-info"
                x-data="snowdogHyvaCheckoutPayNowComponentPaymentMethodPaypo"
            >
                <span>
                    <?= $notice['title'] ?>
                </span>
                <?php if ($notice['content']): ?>
                    <a
                        class="expand"
                        @click="snowdogHyvaCheckoutPayNowComponentPaymentMethodPaypoClick5"
                    >
                        <?= __('Read more') ?>
                    </a>
                    <div
                        x-show="expanded"
                        class="paynow-data-processing-info-more"
                    >
                        <p>
                            <?= $notice['content'] ?>
                        </p>
                    </div>
                <?php endif ?>
            </div>
        <?php endforeach ?>
    </div>
</div>
<script>
<?php /** Generated with hyva-csp-helper.php */ ?>
function snowdogHyvaCheckoutPayNowComponentPaymentMethodPaypo() {
    return Object.assign(
        { expanded: false }
        ,{
            ['snowdogHyvaCheckoutPayNowComponentPaymentMethodPaypoClick5'](event) {return this.expanded = ! this.expanded},
        }
    )
}
window.addEventListener('alpine:init', () => Alpine.data('snowdogHyvaCheckoutPayNowComponentPaymentMethodPaypo', snowdogHyvaCheckoutPayNowComponentPaymentMethodPaypo), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>